import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { validateReleaseAssets } from './validate-release-assets.mjs'

const requiredArtifacts = [
  ['macOS arm64 DMG', '900API_0.2.1_aarch64.dmg'],
  ['macOS Intel DMG', '900API_0.2.1_x64.dmg'],
  ['Linux AppImage', '900API_0.2.1_amd64.AppImage'],
  ['Debian package', '900API_0.2.1_amd64.deb'],
  ['RPM package', '900API-0.2.1-1.x86_64.rpm'],
  ['Windows MSI', '900API_0.2.1_x64_en-US.msi'],
  ['Windows setup executable', '900API_0.2.1_x64-setup.exe'],
] as const

const optionalArchives = [
  '900API_0.2.1_aarch64.app.tar.gz',
  '900API_0.2.1_x64.app.tar.gz',
] as const

describe('release artifact validation', () => {
  let directory = ''

  beforeEach(() => {
    directory = mkdtempSync(join(tmpdir(), '900api-release-assets-'))
  })

  afterEach(() => {
    rmSync(directory, { recursive: true, force: true })
  })

  function writeArtifacts(excludedName?: string) {
    for (const [, file] of requiredArtifacts) {
      if (file !== excludedName) writeFileSync(join(directory, file), 'release artifact')
    }
  }

  it('accepts the complete v0.2.1 set with optional app archives and an existing checksum', () => {
    writeArtifacts()
    for (const file of optionalArchives) writeFileSync(join(directory, file), 'app archive')
    writeFileSync(join(directory, 'SHA256SUMS.txt'), 'old checksums regenerated by the workflow')

    const result = validateReleaseAssets(directory, 'v0.2.1')

    expect(result.version).toBe('0.2.1')
    expect(result.validated).toHaveLength(7)
    expect(result.optionalArchives).toEqual(optionalArchives)
  })

  it.each(requiredArtifacts)('rejects a missing %s', (name, file) => {
    writeArtifacts(file)

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      `Missing required release artifact: ${name}`,
    )
  })

  it('rejects an OtherProduct file masquerading as a required suffix', () => {
    writeArtifacts()
    writeFileSync(join(directory, 'OtherProduct_0.2.1_aarch64.dmg'), 'other product')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      'Unexpected release asset: OtherProduct_0.2.1_aarch64.dmg',
    )
  })

  it('rejects a stale 900API package alongside the current package set', () => {
    writeArtifacts()
    writeFileSync(join(directory, '900API_0.2.0_aarch64.dmg'), 'stale package')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      'Unexpected release asset: 900API_0.2.0_aarch64.dmg',
    )
  })

  it('rejects a stale 900API app archive', () => {
    writeArtifacts()
    writeFileSync(join(directory, '900API_0.2.0_aarch64.app.tar.gz'), 'stale archive')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      'Unexpected release asset: 900API_0.2.0_aarch64.app.tar.gz',
    )
  })

  it('rejects duplicate required artifacts', () => {
    writeArtifacts()
    writeFileSync(join(directory, '900API-0.2.1-2.x86_64.rpm'), 'duplicate RPM')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      'Duplicate required release artifact: RPM package',
    )
  })

  it('rejects an unexpected regular release asset', () => {
    writeArtifacts()
    writeFileSync(join(directory, 'release-notes.txt'), 'unexpected file')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      'Unexpected release asset: release-notes.txt',
    )
  })

  it('rejects an empty expected platform artifact', () => {
    writeArtifacts('900API_0.2.1_x64_en-US.msi')
    writeFileSync(join(directory, '900API_0.2.1_x64_en-US.msi'), '')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      'Windows MSI artifact is empty',
    )
  })

  it.each(optionalArchives)('rejects an empty optional app archive: %s', (file) => {
    writeArtifacts()
    writeFileSync(join(directory, file), '')

    expect(() => validateReleaseAssets(directory, '0.2.1')).toThrow(
      `Optional app archive is empty: ${file}`,
    )
  })
})
